from vllm import LLM, SamplingParams
from vllm.lora.request import LoRARequest

def build_prompt(sample):
    SYSTEM_PROMPT = """
You are a state-of-the-art floor-plan generator that translates JSON specifications and connectivity requirements defined by a bubble diagram into precise, optimized layouts. 
Your algorithm considers each room's dimensions, proportion, and desired adjacencies to produce an efficient arrangement that maximizes usable space while honoring all constraints.
Your top priority is that no two room polygons ever overlap. Rooms must be strictly disjoint, doors may touch room boundaries, but room interiors must never intersect.  

Your output must be a JSON object, where `output` key contains:
- `room_count`: the total number of room and door entries  
- `rooms`: a list of mixing rooms and doors. Each room or door entry in `room` must include:
 - `id`: formatted as `<room_type>|<unique_index>` (e.g. `"bedroom|2"` or `"interior_door|0"`).
 - `room_type`: the room type (e.g. `"living_room"`, `"kitchen"`, etc.)
 - `area` in square meters (all positive numbers)  
 - `floor_polygon`: an ordered list of `{x: , y:}` vertices defining a simple polygon, minimun of 4 vertices, and maximum of 20 vertices. The doors must connect two rooms.

Additional rules:
- **Absolute non-overlap**: no two room polygons may share any interior point under any circumstances.
- Every adjacency in the bubble diagram must be bridged by exactly one door.  
- Every `id` used in the bubble diagram and on any door must appear in the `rooms` list.  

These are 3 examples of the expected output:

1. {'input': {'room_count': 14, 'total_area': 64.1, 'room_types': ['balcony', 'bedroom', 'study_room', 'kitchen', 'living_room', 'bathroom', 'balcony', 'interior_door', 'interior_door', 'interior_door', 'interior_door', 'interior_door', 'interior_door', 'front_door'], 'rooms': [{'id': 'balcony|0', 'room_type': 'balcony', 'width': 3.3, 'height': 1.2, 'is_rectangular': 1}, {'id': 'bedroom', 'room_type': 'bedroom', 'width': 3.1, 'height': 3.2, 'is_rectangular': 1}, {'id': 'study_room', 'room_type': 'study_room', 'width': 2.9, 'height': 2.5, 'is_rectangular': 1}, {'id': 'kitchen', 'room_type': 'kitchen', 'width': 5.3, 'height': 1.5, 'is_rectangular': 1}, {'id': 'living_room', 'room_type': 'living_room', 'width': 5.1, 'height': 8.1, 'is_rectangular': 0}, {'id': 'bathroom', 'room_type': 'bathroom', 'width': 2.2, 'height': 1.5, 'is_rectangular': 1}, {'id': 'balcony|1', 'room_type': 'balcony', 'width': 1.5, 'height': 1.5, 'is_rectangular': 1}, {'id': 'interior_door|0', 'room_type': 'interior_door', 'width': 1.5, 'height': 0.3, 'is_rectangular': 1}, {'id': 'interior_door|1', 'room_type': 'interior_door', 'width': 0.8, 'height': 0.3, 'is_rectangular': 1}, {'id': 'interior_door|2', 'room_type': 'interior_door', 'width': 0.3, 'height': 0.7, 'is_rectangular': 1}, {'id': 'interior_door|3', 'room_type': 'interior_door', 'width': 0.5, 'height': 0.3, 'is_rectangular': 1}, {'id': 'interior_door|4', 'room_type': 'interior_door', 'width': 0.3, 'height': 0.5, 'is_rectangular': 1}, {'id': 'interior_door|5', 'room_type': 'interior_door', 'width': 0.8, 'height': 0.3, 'is_rectangular': 1}, {'id': 'front_door', 'room_type': 'front_door', 'width': 1.5, 'height': 0.3, 'is_rectangular': 1}], 'bubble_diagram': {'balcony|0': ['bedroom'], 'bedroom': ['balcony|0', 'living_room'], 'study_room': ['living_room'], 'kitchen': ['balcony|1', 'living_room'], 'living_room': ['bedroom', 'study_room', 'bathroom', 'kitchen'], 'bathroom': ['living_room'], 'balcony|1': ['kitchen']}}}
   {'output': {'room_count': 14, 'rooms': [{'id': 'balcony|0', 'room_type': 'balcony', 'area': 4.0, 'floor_polygon': [{'x': 10.1, 'y': 14.8}, {'x': 10.1, 'y': 13.6}, {'x': 6.8, 'y': 13.6}, {'x': 6.8, 'y': 14.8}]}, {'id': 'bedroom', 'room_type': 'bedroom', 'area': 9.8, 'floor_polygon': [{'x': 6.8, 'y': 13.2}, {'x': 9.8, 'y': 13.2}, {'x': 9.8, 'y': 10.1}, {'x': 6.8, 'y': 10.1}]}, {'id': 'study_room', 'room_type': 'study_room', 'area': 7.3, 'floor_polygon': [{'x': 5.4, 'y': 7.1}, {'x': 5.4, 'y': 9.6}, {'x': 8.3, 'y': 9.6}, {'x': 8.3, 'y': 7.1}]}, {'id': 'kitchen', 'room_type': 'kitchen', 'area': 8.3, 'floor_polygon': [{'x': 9.5, 'y': 4.7}, {'x': 9.5, 'y': 3.2}, {'x': 4.1, 'y': 3.2}, {'x': 4.1, 'y': 4.7}]}, {'id': 'living_room', 'room_type': 'living_room', 'area': 27.3, 'floor_polygon': [{'x': 10.3, 'y': 9.6}, {'x': 10.3, 'y': 13.2}, {'x': 13.9, 'y': 13.2}, {'x': 13.9, 'y': 7.7}, {'x': 11.2, 'y': 7.7}, {'x': 11.2, 'y': 6.3}, {'x': 9.5, 'y': 6.3}, {'x': 9.5, 'y': 5.1}, {'x': 8.7, 'y': 5.1}, {'x': 8.7, 'y': 9.6}]}, {'id': 'bathroom', 'room_type': 'bathroom', 'area': 3.4, 'floor_polygon': [{'x': 8.3, 'y': 5.1}, {'x': 6.1, 'y': 5.1}, {'x': 6.1, 'y': 6.7}, {'x': 8.3, 'y': 6.7}]}, {'id': 'balcony|1', 'room_type': 'balcony', 'area': 2.4, 'floor_polygon': [{'x': 5.7, 'y': 5.1}, {'x': 4.1, 'y': 5.1}, {'x': 4.1, 'y': 6.7}, {'x': 5.7, 'y': 6.7}]}, {'id': 'interior_door|0', 'room_type': 'interior_door', 'area': 0.4, 'floor_polygon': [{'x': 7.5, 'y': 13.6}, {'x': 9.1, 'y': 13.6}, {'x': 9.1, 'y': 13.3}, {'x': 7.5, 'y': 13.3}]}, {'id': 'interior_door|1', 'room_type': 'interior_door', 'area': 0.2, 'floor_polygon': [{'x': 8.9, 'y': 9.7}, {'x': 8.9, 'y': 10.0}, {'x': 9.8, 'y': 10.0}, {'x': 9.8, 'y': 9.7}]}, {'id': 'interior_door|2', 'room_type': 'interior_door', 'area': 0.2, 'floor_polygon': [{'x': 8.6, 'y': 9.5}, {'x': 8.6, 'y': 8.8}, {'x': 8.4, 'y': 8.8}, {'x': 8.4, 'y': 9.5}]}, {'id': 'interior_door|3', 'room_type': 'interior_door', 'area': 0.1, 'floor_polygon': [{'x': 9.4, 'y': 4.8}, {'x': 8.9, 'y': 4.8}, {'x': 8.9, 'y': 5.1}, {'x': 9.4, 'y': 5.1}]}, {'id': 'interior_door|4', 'room_type': 'interior_door', 'area': 0.1, 'floor_polygon': [{'x': 8.6, 'y': 5.3}, {'x': 8.4, 'y': 5.3}, {'x': 8.4, 'y': 5.8}, {'x': 8.6, 'y': 5.8}]}, {'id': 'interior_door|5', 'room_type': 'interior_door', 'area': 0.2, 'floor_polygon': [{'x': 5.6, 'y': 4.8}, {'x': 4.8, 'y': 4.8}, {'x': 4.8, 'y': 5.1}, {'x': 5.6, 'y': 5.1}]}, {'id': 'front_door', 'room_type': 'front_door', 'area': 0.4, 'floor_polygon': [{'x': 11.3, 'y': 5.9}, {'x': 9.8, 'y': 5.9}, {'x': 9.8, 'y': 6.2}, {'x': 11.3, 'y': 6.2}]}]}}

2. {'input': {'room_count': 10, 'total_area': 64.5, 'room_types': ['bedroom', 'bathroom', 'kitchen', 'bedroom', 'living_room', 'interior_door', 'interior_door', 'interior_door', 'interior_door', 'front_door'], 'rooms': [{'id': 'bedroom|0', 'room_type': 'bedroom', 'width': 3.2, 'height': 4.1, 'is_rectangular': 1}, {'id': 'bathroom', 'room_type': 'bathroom', 'width': 2.0, 'height': 1.6, 'is_rectangular': 1}, {'id': 'kitchen', 'room_type': 'kitchen', 'width': 2.4, 'height': 1.7, 'is_rectangular': 1}, {'id': 'bedroom|1', 'room_type': 'bedroom', 'width': 2.4, 'height': 3.2, 'is_rectangular': 1}, {'id': 'living_room', 'room_type': 'living_room', 'width': 5.0, 'height': 10.3, 'is_rectangular': 0}, {'id': 'interior_door|0', 'room_type': 'interior_door', 'width': 0.1, 'height': 0.8, 'is_rectangular': 1}, {'id': 'interior_door|1', 'room_type': 'interior_door', 'width': 0.6, 'height': 0.1, 'is_rectangular': 1}, {'id': 'interior_door|2', 'room_type': 'interior_door', 'width': 1.5, 'height': 0.1, 'is_rectangular': 1}, {'id': 'interior_door|3', 'room_type': 'interior_door', 'width': 0.7, 'height': 0.3, 'is_rectangular': 1}, {'id': 'front_door', 'room_type': 'front_door', 'width': 0.3, 'height': 0.8, 'is_rectangular': 1}], 'bubble_diagram': {'bedroom|0': ['living_room'], 'bathroom': ['living_room'], 'kitchen': ['living_room'], 'bedroom|1': ['living_room'], 'living_room': ['bedroom|0', 'bathroom', 'kitchen', 'bedroom|1']}}}
   {'output': {'room_count': 10, 'rooms': [{'id': 'bedroom|0', 'room_type': 'bedroom', 'area': 13.2, 'floor_polygon': [{'x': 5.3, 'y': 14.0}, {'x': 8.6, 'y': 14.0}, {'x': 8.6, 'y': 9.9}, {'x': 5.3, 'y': 9.9}]}, {'id': 'bathroom', 'room_type': 'bathroom', 'area': 3.3, 'floor_polygon': [{'x': 7.4, 'y': 9.6}, {'x': 7.4, 'y': 8.0}, {'x': 5.3, 'y': 8.0}, {'x': 5.3, 'y': 9.6}]}, {'id': 'kitchen', 'room_type': 'kitchen', 'area': 4.0, 'floor_polygon': [{'x': 11.5, 'y': 2.9}, {'x': 9.1, 'y': 2.9}, {'x': 9.1, 'y': 4.6}, {'x': 11.5, 'y': 4.6}]}, {'id': 'bedroom|1', 'room_type': 'bedroom', 'area': 7.6, 'floor_polygon': [{'x': 8.6, 'y': 4.4}, {'x': 6.3, 'y': 4.4}, {'x': 6.3, 'y': 7.6}, {'x': 8.6, 'y': 7.6}]}, {'id': 'living_room', 'room_type': 'living_room', 'area': 35.6, 'floor_polygon': [{'x': 9.1, 'y': 4.9}, {'x': 9.1, 'y': 8.0}, {'x': 7.7, 'y': 8.0}, {'x': 7.7, 'y': 9.6}, {'x': 9.0, 'y': 9.6}, {'x': 9.0, 'y': 15.1}, {'x': 12.7, 'y': 15.1}, {'x': 12.7, 'y': 8.1}, {'x': 11.5, 'y': 8.1}, {'x': 11.5, 'y': 4.9}]}, {'id': 'interior_door|0', 'room_type': 'interior_door', 'area': 0.1, 'floor_polygon': [{'x': 7.5, 'y': 9.3}, {'x': 7.6, 'y': 9.3}, {'x': 7.6, 'y': 8.4}, {'x': 7.5, 'y': 8.4}]}, {'id': 'interior_door|1', 'room_type': 'interior_door', 'area': 0.1, 'floor_polygon': [{'x': 7.9, 'y': 9.8}, {'x': 8.5, 'y': 9.8}, {'x': 8.5, 'y': 9.7}, {'x': 7.9, 'y': 9.7}]}, {'id': 'interior_door|2', 'room_type': 'interior_door', 'area': 0.2, 'floor_polygon': [{'x': 9.4, 'y': 4.6}, {'x': 9.4, 'y': 4.8}, {'x': 11.0, 'y': 4.8}, {'x': 11.0, 'y': 4.6}]}, {'id': 'interior_door|3', 'room_type': 'interior_door', 'area': 0.2, 'floor_polygon': [{'x': 7.9, 'y': 7.7}, {'x': 7.9, 'y': 7.9}, {'x': 8.6, 'y': 7.9}, {'x': 8.6, 'y': 7.7}]}, {'id': 'front_door', 'room_type': 'front_door', 'area': 0.2, 'floor_polygon': [{'x': 11.5, 'y': 6.8}, {'x': 11.5, 'y': 7.7}, {'x': 11.8, 'y': 7.7}, {'x': 11.8, 'y': 6.8}]}]}}

3. {'input': {'room_count': 16, 'total_area': 77.9, 'room_types': ['bedroom', 'study_room', 'kitchen', 'balcony', 'bathroom', 'bedroom', 'living_room', 'balcony', 'interior_door', 'interior_door', 'interior_door', 'interior_door', 'interior_door', 'interior_door', 'interior_door', 'front_door'], 'rooms': [{'id': 'bedroom|0', 'room_type': 'bedroom', 'width': 2.5, 'height': 4.9, 'is_rectangular': 0}, {'id': 'study_room', 'room_type': 'study_room', 'width': 2.0, 'height': 2.7, 'is_rectangular': 1}, {'id': 'kitchen', 'room_type': 'kitchen', 'width': 1.5, 'height': 2.7, 'is_rectangular': 1}, {'id': 'balcony|0', 'room_type': 'balcony', 'width': 3.9, 'height': 1.1, 'is_rectangular': 1}, {'id': 'bathroom', 'room_type': 'bathroom', 'width': 1.3, 'height': 2.4, 'is_rectangular': 1}, {'id': 'bedroom|1', 'room_type': 'bedroom', 'width': 2.9, 'height': 4.5, 'is_rectangular': 1}, {'id': 'living_room', 'room_type': 'living_room', 'width': 5.1, 'height': 8.4, 'is_rectangular': 0}, {'id': 'balcony|1', 'room_type': 'balcony', 'width': 3.6, 'height': 0.9, 'is_rectangular': 1}, {'id': 'interior_door|0', 'room_type': 'interior_door', 'width': 0.8, 'height': 0.3, 'is_rectangular': 1}, {'id': 'interior_door|1', 'room_type': 'interior_door', 'width': 0.7, 'height': 0.3, 'is_rectangular': 1}, {'id': 'interior_door|2', 'room_type': 'interior_door', 'width': 0.7, 'height': 0.3, 'is_rectangular': 1}, {'id': 'interior_door|3', 'room_type': 'interior_door', 'width': 0.6, 'height': 0.3, 'is_rectangular': 1}, {'id': 'interior_door|4', 'room_type': 'interior_door', 'width': 0.3, 'height': 0.8, 'is_rectangular': 1}, {'id': 'interior_door|5', 'room_type': 'interior_door', 'width': 0.8, 'height': 0.3, 'is_rectangular': 1}, {'id': 'interior_door|6', 'room_type': 'interior_door', 'width': 0.8, 'height': 0.3, 'is_rectangular': 1}, {'id': 'front_door', 'room_type': 'front_door', 'width': 0.3, 'height': 0.8, 'is_rectangular': 1}], 'bubble_diagram': {'bedroom|0': ['living_room'], 'study_room': ['living_room'], 'kitchen': ['living_room', 'balcony|0'], 'balcony|0': ['kitchen'], 'bathroom': ['living_room'], 'bedroom|1': ['living_room'], 'living_room': ['bedroom|0', 'study_room', 'kitchen', 'bathroom', 'bedroom|1', 'balcony|1'], 'balcony|1': ['living_room']}}}
   {'output': {'room_count': 16, 'rooms': [{'id': 'bedroom|0', 'room_type': 'bedroom', 'area': 10.4, 'floor_polygon': [{'x': 9.9, 'y': 8.3}, {'x': 10.7, 'y': 8.3}, {'x': 10.7, 'y': 7.1}, {'x': 12.4, 'y': 7.1}, {'x': 12.4, 'y': 3.4}, {'x': 9.9, 'y': 3.4}]}, {'id': 'study_room', 'room_type': 'study_room', 'area': 5.3, 'floor_polygon': [{'x': 7.5, 'y': 6.0}, {'x': 9.5, 'y': 6.0}, {'x': 9.5, 'y': 3.4}, {'x': 7.5, 'y': 3.4}]}, {'id': 'kitchen', 'room_type': 'kitchen', 'area': 4.1, 'floor_polygon': [{'x': 7.1, 'y': 6.0}, {'x': 7.1, 'y': 3.4}, {'x': 5.6, 'y': 3.4}, {'x': 5.6, 'y': 6.0}]}, {'id': 'balcony|0', 'room_type': 'balcony', 'area': 4.4, 'floor_polygon': [{'x': 5.6, 'y': 3.0}, {'x': 9.5, 'y': 3.0}, {'x': 9.5, 'y': 1.8}, {'x': 5.6, 'y': 1.8}]}, {'id': 'bathroom', 'room_type': 'bathroom', 'area': 3.2, 'floor_polygon': [{'x': 11.1, 'y': 9.9}, {'x': 12.4, 'y': 9.9}, {'x': 12.4, 'y': 7.5}, {'x': 11.1, 'y': 7.5}]}, {'id': 'bedroom|1', 'room_type': 'bedroom', 'area': 13.0, 'floor_polygon': [{'x': 9.6, 'y': 10.3}, {'x': 9.6, 'y': 14.8}, {'x': 12.4, 'y': 14.8}, {'x': 12.4, 'y': 10.3}]}, {'id': 'living_room', 'room_type': 'living_room', 'area': 32.6, 'floor_polygon': [{'x': 5.6, 'y': 14.8}, {'x': 9.1, 'y': 14.8}, {'x': 9.1, 'y': 9.9}, {'x': 10.7, 'y': 9.9}, {'x': 10.7, 'y': 8.7}, {'x': 9.5, 'y': 8.7}, {'x': 9.5, 'y': 6.5}, {'x': 5.6, 'y': 6.5}]}, {'id': 'balcony|1', 'room_type': 'balcony', 'area': 3.3, 'floor_polygon': [{'x': 9.1, 'y': 15.3}, {'x': 5.6, 'y': 15.3}, {'x': 5.6, 'y': 16.2}, {'x': 9.1, 'y': 16.2}]}, {'id': 'interior_door|0', 'room_type': 'interior_door', 'area': 0.2, 'floor_polygon': [{'x': 6.2, 'y': 3.0}, {'x': 6.2, 'y': 3.3}, {'x': 7.0, 'y': 3.3}, {'x': 7.0, 'y': 3.0}]}, {'id': 'interior_door|1', 'room_type': 'interior_door', 'area': 0.2, 'floor_polygon': [{'x': 7.7, 'y': 6.1}, {'x': 7.7, 'y': 6.4}, {'x': 8.4, 'y': 6.4}, {'x': 8.4, 'y': 6.1}]}, {'id': 'interior_door|2', 'room_type': 'interior_door', 'area': 0.2, 'floor_polygon': [{'x': 10.6, 'y': 8.6}, {'x': 10.6, 'y': 8.4}, {'x': 9.9, 'y': 8.4}, {'x': 9.9, 'y': 8.6}]}, {'id': 'interior_door|3', 'room_type': 'interior_door', 'area': 0.2, 'floor_polygon': [{'x': 6.4, 'y': 6.4}, {'x': 7.0, 'y': 6.4}, {'x': 7.0, 'y': 6.1}, {'x': 6.4, 'y': 6.1}]}, {'id': 'interior_door|4', 'room_type': 'interior_door', 'area': 0.2, 'floor_polygon': [{'x': 11.0, 'y': 9.8}, {'x': 11.0, 'y': 8.9}, {'x': 10.8, 'y': 8.9}, {'x': 10.8, 'y': 9.8}]}, {'id': 'interior_door|5', 'room_type': 'interior_door', 'area': 0.2, 'floor_polygon': [{'x': 9.8, 'y': 10.0}, {'x': 9.8, 'y': 10.3}, {'x': 10.6, 'y': 10.3}, {'x': 10.6, 'y': 10.0}]}, {'id': 'interior_door|6', 'room_type': 'interior_door', 'area': 0.2, 'floor_polygon': [{'x': 7.0, 'y': 15.2}, {'x': 7.0, 'y': 14.9}, {'x': 6.2, 'y': 14.9}, {'x': 6.2, 'y': 15.2}]}, {'id': 'front_door', 'room_type': 'front_door', 'area': 0.2, 'floor_polygon': [{'x': 5.5, 'y': 8.3}, {'x': 5.5, 'y': 7.5}, {'x': 5.2, 'y': 7.5}, {'x': 5.2, 'y': 8.3}]}]}}
   
   Return only a JSON object containing an `output` key without extra commentary or explanation. Veriify with code if it has overlaps if yes try again.
"""

    system_prompt = (
        f"<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n {SYSTEM_PROMPT} \n"
    )
    prompt = (
        f"<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n"
        f"{system_prompt}<|eot_id|><|start_header_id|>user<|end_header_id|>\n"
        f"{sample}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n"
    )
    return prompt

model_path = "models/Llama-4-Scout-17B-16E-Instruct"
# lora_adapter_path = "/home/l/luislara/links/scratch/ds2d_v2/output/rplan_3_70B/"

model = LLM(model=model_path, tensor_parallel_size=4, device="cuda", max_model_len=100_000, 
            override_generation_config= {
                "attn_temperature_tuning": True,
            }
            # enable_lora=True
        )
# lora = LoRARequest("lora_adapter", 1, lora_adapter_path)
sampling_params = SamplingParams(max_tokens=4096)

sample = """
{'input': {'room_count': 10, 'total_area': 72.4, 'rooms': [{'id': 'living_room', 'room_type': 'living_room', 'width': 7.0, 'height': 5.2, 'is_rectangular': 0}, {'id': 'bedroom|0', 'room_type': 'bedroom', 'width': 3.6, 'height': 3.0, 'is_rectangular': 1}, {'id': 'bedroom|1', 'room_type': 'bedroom', 'width': 3.2, 'height': 4.1, 'is_rectangular': 1}, {'id': 'bathroom', 'room_type': 'bathroom', 'width': 2.2, 'height': 2.6, 'is_rectangular': 1}, {'id': 'kitchen', 'room_type': 'kitchen', 'width': 3.6, 'height': 2.6, 'is_rectangular': 1}, {'id': 'interior_door|0', 'room_type': 'interior_door', 'width': 1.5, 'height': 0.1, 'is_rectangular': 1}, {'id': 'interior_door|1', 'room_type': 'interior_door', 'width': 0.1, 'height': 0.6, 'is_rectangular': 1}, {'id': 'interior_door|2', 'room_type': 'interior_door', 'width': 1.5, 'height': 0.1, 'is_rectangular': 1}, {'id': 'interior_door|3', 'room_type': 'interior_door', 'width': 0.1, 'height': 0.8, 'is_rectangular': 1}, {'id': 'front_door', 'room_type': 'front_door', 'width': 0.1, 'height': 0.8, 'is_rectangular': 1}], 'bubble_diagram': {'living_room': ['bedroom|1', 'kitchen', 'bedroom|0'], 'bedroom|0': ['living_room'], 'bedroom|1': ['living_room'], 'bathroom': ['kitchen'], 'kitchen': ['living_room', 'bathroom']}}}
"""

outputs = model.generate(
    [build_prompt(sample)], 
    sampling_params, 
    # lora_request=lora
)
print(outputs[0].outputs[0].text)
